services:
  postgres:
    image: postgres:latest
    command: ["docker-entrypoint.sh", "postgres", "-c", "max_connections=300"]
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rssagg
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  my_postgres_data:
